const cool = require('cool-ascii-faces')
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const path = require('path')
const PORT = process.env.PORT || 5000

const botController = require('./controllers/messengerBotController')

app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/cool', (req, res) => res.send(cool()))
  .get('/db', botController.testDb)
  .get('/messenger-bot-load', botController.messengerLoad)
  .get('/messages', botController.allMessages)
  .get('/messages/:id', botController.showMessage)
  .get('/messages/:id/delete', botController.deleteMessage)
  .delete('/messages/:id', botController.deleteMessage)
  .post('/messenger-bot-message', botController.handleMessage)
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
